### ISSUE TITLE
Problems when using multiple SqlDependenciesEx

### ISSUE THREAD

**Issue by SimoneMSR** [dyatchenko/ServiceBrokerListener#17] opened 2016-05-06 12:33 UTC
I am using concurrently two instances of SqlDependencyEx with two different callback. It seems however that
1) when the 1° dependency fires, both the 1° and 2° callbacks are called
2) the 2° dependency never fires (even if the db has changed)

This is not what I am expecting from the code below. Where am I wrong?

NOTE: I have forced the two dependencies to have different Identity-es

```
this.sqlDependencyMailSent = new SqlDependencyEx(
                           ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString,
                           "costerdb",
                           "PLAN_AlarmRelayQueue",
                           "dbo",
                           SqlDependencyEx.NotificationTypes.Delete,true,0);
            this.sqlDependencyMailSent.TableChanged += onMailSent;
            this.enqueuedId = -1;
            if(!this.sqlDependencyMailSent.Active)
                this.sqlDependencyMailSent.Start();

            this.sqlDependencyMailAcked = new SqlDependencyEx(
                                               ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString,
                                               "costerdb",
                                               "PLAN_AlarmRelayAck",
                                               "dbo",
                                               SqlDependencyEx.NotificationTypes.Insert,true,1);

            this.sqlDependencyMailAcked.TableChanged += onMailNotified;
            if (!this.sqlDependencyMailAcked.Active)
                `this.sqlDependencyMailAcked.Start();
```

**Comment by dyatchenko** [comment] 2016-05-13 16:34
Hi Simone,

Thanks for the issue and sorry for the delay. I was unable to reproduce your problem. I created a unit-test with the following code (copied from yours):



        [Test]
        public void TwoTablesNotificationsTest()
        {
            int table1InsertsReceived = 0;
            int table1DeletesReceived = 0;

            int table2InsertsReceived = 0;
            int table2DeletesReceived = 0;

            using (var sqlDependencyFirstTable = new SqlDependencyEx(
                           TEST_CONNECTION_STRING,
                           "TestDatabase",
                           "TestTable",
                           "temp",
                           SqlDependencyEx.NotificationTypes.Delete,
                           true,
                           0))
            {

                sqlDependencyFirstTable.TableChanged += (sender, args) =>
                {
                    if (args.NotificationType == SqlDependencyEx.NotificationTypes.Delete)
                    {
                        table1DeletesReceived++;
                    }

                    if (args.NotificationType == SqlDependencyEx.NotificationTypes.Insert)
                    {
                        table1InsertsReceived++;
                    }
                };

                if (!sqlDependencyFirstTable.Active)
                    sqlDependencyFirstTable.Start();

                using (var sqlDependencySecondTable = new SqlDependencyEx(
                                                   TEST_CONNECTION_STRING,
                                                   "TestDatabase",
                                                   "TestTable",
                                                   "temp2",
                                                   SqlDependencyEx.NotificationTypes.Insert,
                                                   true,
                                                   1))
                {

                    sqlDependencySecondTable.TableChanged += (sender, args) =>
                    {
                        if (args.NotificationType == SqlDependencyEx.NotificationTypes.Delete)
                        {
                            table2DeletesReceived++;
                        }

                        if (args.NotificationType == SqlDependencyEx.NotificationTypes.Insert)
                        {
                            table2InsertsReceived++;
                        }
                    };

                    if (!sqlDependencySecondTable.Active)
                        sqlDependencySecondTable.Start();

                    MakeChunkedInsert(5, TEST_TABLE_1_FULL_NAME);
                    MakeChunkedInsert(3, TEST_TABLE_2_FULL_NAME);

                    DeleteFirstRow(TEST_TABLE_1_FULL_NAME);
                    DeleteFirstRow(TEST_TABLE_1_FULL_NAME);
                    DeleteFirstRow(TEST_TABLE_1_FULL_NAME);
                    DeleteFirstRow(TEST_TABLE_1_FULL_NAME);

                    DeleteFirstRow(TEST_TABLE_2_FULL_NAME);
                    DeleteFirstRow(TEST_TABLE_2_FULL_NAME);

                    // Wait for notification to complete
                    Thread.Sleep(3000);
                }
            }

            Assert.AreEqual(4, table1DeletesReceived);
            Assert.AreEqual(0, table1InsertsReceived);

            Assert.AreEqual(1, table2InsertsReceived);
            Assert.AreEqual(0, table2DeletesReceived);
        }

As you can see here I insert/delete here in two different tables simultaneously and receive correct notification numbers.
Here is the test result:

![image](https://cloud.githubusercontent.com/assets/10171967/15254825/912ac400-18ed-11e6-9dba-97ee18443f03.png)

You might need to dispose the listeners correctly and create them again.

Thanks,
Dmitrii

**Comment by dyatchenko** [comment] 2016-05-24 00:13
If you don't have any comments on this, I'm closing the issue.

**Closed by dyatchenko** 2016-05-24 00:13 UTC

**Comment by SimoneMSR** [comment] 2016-05-24 10:54
Sorry for not replying. But I solved the problem (synchronize threads) using native c# events (System.Threading.AutoresetEvent) and Rest API
